In [1]:
import pandas as pd

In [3]:
import pandas as pd

# Helper function to convert Google Sheets URL to CSV export URL
def gsheet_to_csv_url(url):
    if "/edit" in url:
        base = url.split("/edit")[0]
        gid = "0"
        if "gid=" in url:
            gid = url.split("gid=")[-1].split("#")[0]
        return f"{base}/export?format=csv&gid={gid}"
    return url

# List of (year, url) tuples
sheet_links = [
    ("2023", "https://docs.google.com/spreadsheets/d/1zlh79aLdicsDVjZoxfwVm8SY1iFlKm-GBI34TMk1I30/edit?usp=sharing"),
    ("2022", "https://docs.google.com/spreadsheets/d/1mmsehBjl-V1eVueiCJEjFV6PhM6eKaCCPFIfcrk7IKk/edit?gid=0#gid=0"),
    ("2021", "https://docs.google.com/spreadsheets/d/1E-Suwl9z_e8-W1JuP5HVmIKv6C4mpd73pFpgtCdrTkQ/edit?gid=0#gid=0"),
    ("2020", "https://docs.google.com/spreadsheets/d/1Q5M7Zw_A-Kn2V7csyxGqleVXWliLVQ4e080aNI7oIiE/edit?gid=969721861#gid=969721861"),
    ("2019", "https://docs.google.com/spreadsheets/d/1mY0ckZ7AKwlgeZv5uMA6eah7QwabyPv47SGNuqrO20I/edit?gid=969721861#gid=969721861"),
    ("2018", "https://docs.google.com/spreadsheets/d/1nV6SU6eGIzi0_tz6ccezkEmtJewfioq3/edit?gid=1198915962#gid=1198915962"),
    ("2017", "https://data.colorado.gov/api/v3/views/uhi6-hddy/query.csv"),
    ("2016", "https://data.colorado.gov/api/v3/views/m8vm-brgw/query.csv"),
    ("Licensing", "https://docs.google.com/spreadsheets/d/1q5PSJaDc-cpfKXBn6tQbg0jVxvwyrCNZUBk-5CCortA/edit?gid=531274251#gid=531274251"),
]

# Download and load each sheet as a DataFrame
dfs = {}
for year, url in sheet_links:
    csv_url = gsheet_to_csv_url(url)
    try:
        dfs[year] = pd.read_csv(csv_url)
        print(f"Loaded {year} data: {dfs[year].shape}")
    except Exception as e:
        print(f"Failed to load {year}: {e}")

# Example: display the first few rows of 2022 data
dfs["2022"].head()

Loaded 2023 data: (347, 154)
Loaded 2022 data: (369, 154)
Loaded 2021 data: (354, 154)
Loaded 2020 data: (356, 154)
Loaded 2019 data: (349, 154)
Loaded 2018 data: (329, 173)
Failed to load 2017: HTTP Error 403: Forbidden
Failed to load 2016: HTTP Error 403: Forbidden
Loaded Licensing data: (2967, 7)

,Facility Name,1/1/2022\n Adult Dogs\n In Shelter,1/1/2022\n Adult Dogs\n In Foster Care,2022\n Adult Dogs\n Stray,2022\n Adult Dogs\n Owner Relinquished,2022\n Adult Dogs\n Transfer from another Colorado Organization,2022\n Adult Dogs\n Transfer from Out of State,2022\n Adult Dogs\n Other,2022\n Adult Dogs\n Adoption,2022\n Adult Dogs\n Returned to Owner (RTO),...,2022\n Other\n Adoption,2022\n Other\n Returned to Owner (RTO),2022\n Other\n Transfer to another Colorado Organization,2022\n Other\n Transfer to Out of State,2022\n Other\n Other.1,2022\n Other\n Deaths,2022\n Other\n Euthanasia,2022\n Other\n Missing/Stolen,12/31/2022\n Other\n In Shelter,12/31/2022\n Other\n In Foster Care
0,"2 Blondes All Breed Rescue, Inc.",38,65,0,4,7,329,106,426,0,...,0,0,0,0,0,0,0,0,0,0
1,2nd Chance Vizsla Rescue Inc,0,9,0,3,0,0,0,5,0,...,0,0,0,0,0,0,0,0,0,0
2,4 Paws 4 Life Rescue,0,14,66,0,59,193,0,317,0,...,0,0,0,0,0,0,0,0,0,0
3,7 Paws Rescue Ranch,0,0,0,0,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9 Lives Rescue,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
import pandas as pd

# Helper function to convert Google Sheets URL to CSV export URL, skip API endpoints
def gsheet_to_csv_url(url):
    if url.endswith('.csv'):
        return url
    if "/edit" in url:
        base = url.split("/edit")[0]
        gid = "0"
        if "gid=" in url:
            gid = url.split("gid=")[-1].split("#")[0]
        return f"{base}/export?format=csv&gid={gid}"
    return url

# List of (year, url) tuples
sheet_links = [
    ("2023", "https://docs.google.com/spreadsheets/d/1zlh79aLdicsDVjZoxfwVm8SY1iFlKm-GBI34TMk1I30/edit?usp=sharing"),
    ("2022", "https://docs.google.com/spreadsheets/d/1mmsehBjl-V1eVueiCJEjFV6PhM6eKaCCPFIfcrk7IKk/edit?gid=0#gid=0"),
    ("2021", "https://docs.google.com/spreadsheets/d/1E-Suwl9z_e8-W1JuP5HVmIKv6C4mpd73pFpgtCdrTkQ/edit?gid=0#gid=0"),
    ("2020", "https://docs.google.com/spreadsheets/d/1Q5M7Zw_A-Kn2V7csyxGqleVXWliLVQ4e080aNI7oIiE/edit?gid=969721861#gid=969721861"),
    ("2019", "https://docs.google.com/spreadsheets/d/1mY0ckZ7AKwlgeZv5uMA6eah7QwabyPv47SGNuqrO20I/edit?gid=969721861#gid=969721861"),
    ("2018", "https://docs.google.com/spreadsheets/d/1nV6SU6eGIzi0_tz6ccezkEmtJewfioq3/edit?gid=1198915962#gid=1198915962"),
    ("2017", "https://data.colorado.gov/api/v3/views/uhi6-hddy/query.csv"),
    ("2016", "https://data.colorado.gov/api/v3/views/m8vm-brgw/query.csv"),
    ("Licensing", "https://docs.google.com/spreadsheets/d/1q5PSJaDc-cpfKXBn6tQbg0jVxvwyrCNZUBk-5CCortA/edit?gid=531274251#gid=531274251"),
]

# Download and load each sheet as a DataFrame
dfs = {}
for year, url in sheet_links:
    csv_url = gsheet_to_csv_url(url)
    try:
        dfs[year] = pd.read_csv(csv_url)
        print(f"Loaded {year} data: {dfs[year].shape}")
    except Exception as e:
        print(f"Failed to load {year}: {e}")

# Example: display the first few rows of 2022 data
dfs["2022"].head()

Loaded 2023 data: (347, 154)
Loaded 2022 data: (369, 154)
Loaded 2021 data: (354, 154)
Loaded 2020 data: (356, 154)
Loaded 2019 data: (349, 154)
Loaded 2018 data: (329, 173)
Failed to load 2017: HTTP Error 403: Forbidden
Failed to load 2016: HTTP Error 403: Forbidden
Loaded Licensing data: (2967, 7)

,Facility Name,1/1/2022\n Adult Dogs\n In Shelter,1/1/2022\n Adult Dogs\n In Foster Care,2022\n Adult Dogs\n Stray,2022\n Adult Dogs\n Owner Relinquished,2022\n Adult Dogs\n Transfer from another Colorado Organization,2022\n Adult Dogs\n Transfer from Out of State,2022\n Adult Dogs\n Other,2022\n Adult Dogs\n Adoption,2022\n Adult Dogs\n Returned to Owner (RTO),...,2022\n Other\n Adoption,2022\n Other\n Returned to Owner (RTO),2022\n Other\n Transfer to another Colorado Organization,2022\n Other\n Transfer to Out of State,2022\n Other\n Other.1,2022\n Other\n Deaths,2022\n Other\n Euthanasia,2022\n Other\n Missing/Stolen,12/31/2022\n Other\n In Shelter,12/31/2022\n Other\n In Foster Care
0,"2 Blondes All Breed Rescue, Inc.",38,65,0,4,7,329,106,426,0,...,0,0,0,0,0,0,0,0,0,0
1,2nd Chance Vizsla Rescue Inc,0,9,0,3,0,0,0,5,0,...,0,0,0,0,0,0,0,0,0,0
2,4 Paws 4 Life Rescue,0,14,66,0,59,193,0,317,0,...,0,0,0,0,0,0,0,0,0,0
3,7 Paws Rescue Ranch,0,0,0,0,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9 Lives Rescue,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#2023
'https://docs.google.com/spreadsheets/d/1zlh79aLdicsDVjZoxfwVm8SY1iFlKm-GBI34TMk1I30/edit?usp=sharing'
#2022
'https://docs.google.com/spreadsheets/d/1mmsehBjl-V1eVueiCJEjFV6PhM6eKaCCPFIfcrk7IKk/edit?gid=0#gid=0'
#2021
'https://docs.google.com/spreadsheets/d/1E-Suwl9z_e8-W1JuP5HVmIKv6C4mpd73pFpgtCdrTkQ/edit?gid=0#gid=0'
#2020
'https://docs.google.com/spreadsheets/d/1Q5M7Zw_A-Kn2V7csyxGqleVXWliLVQ4e080aNI7oIiE/edit?gid=969721861#gid=969721861'
#2019
'https://docs.google.com/spreadsheets/d/1mY0ckZ7AKwlgeZv5uMA6eah7QwabyPv47SGNuqrO20I/edit?gid=969721861#gid=969721861'
#2018
'https://docs.google.com/spreadsheets/d/1nV6SU6eGIzi0_tz6ccezkEmtJewfioq3/edit?gid=1198915962#gid=1198915962'

#API endpoint
#2017
'https://data.colorado.gov/api/v3/views/uhi6-hddy/query.csv'
#2016
'https://data.colorado.gov/api/v3/views/m8vm-brgw/query.csv'

#Licensing
'https://docs.google.com/spreadsheets/d/1q5PSJaDc-cpfKXBn6tQbg0jVxvwyrCNZUBk-5CCortA/edit?gid=531274251#gid=531274251'